export enum MSClass {
  Adele = 'Adele',
  AngelicBuster = 'Angelic Buster',
  Aran = 'Aran',
  Ark = 'Ark',
  BattleMage = 'Battle Mage',
  BeastTamer = 'Beast Tamer',
  Bishop = 'Bishop',
  Blaster = 'Blaster',
  BlazeWizard = 'Blaze Wizard',
  BowMaster = 'Bow Master',
  Buccaneer = 'Buccaneer',
  Cadena = 'Cadena',
  Cannoneer = 'Cannoneer',
  Corsair = 'Corsair',
  DarkKnight = 'Dark Knight',
  DawnWarrior = 'Dawn Warrior',
  DemonSlayer = 'Demon Slayer',
  DualBlade = 'Dual Blade',
  Evan = 'Evan',
  FirePoisionMagician = 'Fire/Posion Magician',
  Hayato = 'Hayato',
  Hero = 'Hero',
  Hoyoung = 'Hoyoung',
  IceLightningMagician = 'Ice / Lightning Magician',
  Illium = 'Illium',
  Jett = 'Jett',
  Luminous = 'Luminous',
  Kaiser = 'Kaiser',
  Kanna = 'Kanna',
  Kinesis = 'Kinesis',
  Marksman = 'Marksman',
  Mechanic = 'Mechanic',
  Mercedes = 'Mercedes',
  Mihile = 'Mihile',
  NightLord = 'Night Lord',
  NightWalker = 'Night Walker',
  Paladin = 'Paladin',
  PathFinder = 'Path Finder',
  Phantom = 'Phantom',
  Shade = 'Shade',
  Shadower = 'Shadower',
  ThunderBreaker = 'Thunder Breaker',
  Kain = 'Kain',
  WildHunter = 'Wild Hunter',
  WindArcher = 'Wind Archer',
  Xenon = 'Xenon',
  Zero = 'Zero',
}

export enum MSClassBranch {
  BowMan = 'Bow Man',
  Magician = 'Magician',
  Pirate = 'Pirate',
  Thief = 'Thief',
  Warrior = 'Warrior',
}
