export enum Class {
  Adele = 'ADELE',
  AngelicBuster = 'ANGELIC_BUSTER',
  Aran = 'ARAN',
  Ark = 'ARK',
  BattleMage = 'BATTLE_MAGE',
  BeastTamer = 'BEAST_TAMER',
  Bishop = 'BISHOP',
  Blaster = 'BLASTER',
  BlazeWizard = 'BLAZE_WIZARD',
  BowMaster = 'BOW_MASTER',
  Buccaneer = 'BUCCANEER',
  Cadena = 'CADENA',
  Cannoneer = 'Cannoneer',
  Corsair = 'CORSAIR',
  DarkKnight = 'DARK_KNIGHT',
  DawnWarrior = 'DAWN_WARRIOR',
  DemonSlayer = 'DEMON_SLAYER',
  DualBlade = 'DUAL_BLADE',
  Evan = 'EVAN',
  FirePoisionMagician = 'FIRE_POISION_MAGICIAN',
  Hayato = 'HAYATO',
  Hero = 'HERO',
  Hoyoung = 'HOYOUNG',
  IceLightningMagician = 'ICE_LIGHTNING_MAGICIAN',
  Illium = 'ILLIUM',
  Jett = 'JETT',
  Luminous = 'LUMINOUS',
  Kaiser = 'KAISER',
  Kanna = 'KANNA',
  Kinesis = 'KINESIS',
  Marksman = 'MARKSMAN',
  Mechanic = 'MECHANIC',
  Mercedes = 'MERCEDES',
  Mihile = 'MIHILE',
  NightLord = 'NIGHT_LORD',
  NightWalker = 'NIGHT_WALKER',
  Paladin = 'PALADIN',
  PathFinder = 'PATHFINDER',
  Phantom = 'PHANTOM',
  Shade = 'SHADE',
  Shadower = 'SHADOWER',
  ThunderBreaker = 'THUNDER_BREAKER',
  Kain = 'KAIN',
  WildHunter = 'WILD_HUNTER',
  WindArcher = 'WIND_ARCHER',
  Xenon = 'XENON',
  Zero = 'ZERO',
}

export enum ClassBranch {
  Bowman = 'BOWMAN',
  Magician = 'MAGICIAN',
  Pirate = 'PIRATE',
  Thief = 'THIEF',
  Warrior = 'WARRIOR',
}
